# Generated by Django 2.2 on 2020-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, default='文章摘要等同于网页description内容，请务必填写...', max_length=200, verbose_name='文章摘要'),
        ),
    ]
