# Generated by Django 2.2 on 2020-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200717_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='网站描述')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='友链地址')),
                ('logo', models.URLField(blank=True, help_text='请填写http或https开头的完整形式地址', verbose_name='网站LOGO')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否首页展示')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', '左边'), ('R', '右边')], default='L', max_length=1, verbose_name='位置')),
                ('star_num', models.IntegerField(choices=[(1, '1颗星'), (2, '2颗星'), (3, '3颗星'), (4, '4颗星'), (5, '5颗星')], default=3, verbose_name='星星个数')),
                ('icon', models.CharField(default='fa fa-pencil', max_length=50, verbose_name='图标')),
                ('icon_color', models.CharField(choices=[('primary', '基本-蓝色'), ('success', '成功-绿色'), ('info', '信息-天蓝色'), ('warning', '警告-橙色'), ('danger', '危险-红色')], default='info', max_length=20, verbose_name='图标颜色')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('update_date', models.DateTimeField(verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='主要内容')),
            ],
            options={
                'verbose_name': '时间线',
                'verbose_name_plural': '时间线',
                'ordering': ['update_date'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300, verbose_name='文章摘要'),
        ),
    ]
