# Generated by Django 2.2 on 2020-07-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200727_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlink',
            options={'ordering': ['created_time'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.RenameField(
            model_name='friendlink',
            old_name='create_date',
            new_name='created_time',
        ),
    ]
